export const pageTitle = {
  tradeItemDocuments: "Траспортные единицы",
  warehouseProducts: "Товары",
  inbound: "Заказы приемки",
  outbound: "Заказы отгрузки",
  shipments: "Отгрузки",
  pickingOrders: "Заказы сборки",
  productCatalog: "Карточка товара",
  users: "Пользователи",
  warehouseMap: "Карта склада",
  partners: "Партнеры",
  warehouses: "Склады",
  cellTypes: "Типы ячеек",
  backgroundTasks: "Фоновые процессы",
  periodicReservations: "Периодические резервации",
  productsTree: "Дерево товаров",
  tradeItems: "Типы ТЕ",
  erpWarehouses: "Склады ERP",
  measureUnits: "Единицы измерения",
  equipments: "Типы оборудования",
  popularities: "Типы зоны популярности",
  commodities: "Типы зоны хранения",
  couriers: "Курьеры",
  pickingPriorities: "Приоритет направлении",
};

export const GroupPrivileges = {
  JobsBrw: "Фоновые процессы",
  Adjustmentsbrw: "Уточнения",
  OrderServicesBrw: "Услуги",
  ServicesBrw: "Услуги",
  SkuPack: "Упаковки товаров",
  TransportFunctionBrw: "Транспортные операции",
  Containersbrw: "Транспортные единицы",
  InventoryLocationTreeBrw: "Товары",
  LocTypeBrw: "Типы ячеек",
  EquipmentTypesbrw: "Типы оборудования",
  RoutingTypesBrw: "Типы маршрутизации",
  CourierDeliveryTypesBrw: "Типы доставок",
  HoldTypesBrw: "Типы блокировки",
  PackTypebrw: "Типы ТЕ",
  GuiBatchSortingBrw: "Терминал упаковки",
  BrowserInvoices: "ТТН",
  Countries: "Страны",
  ResourceClientTranslations: "Создать детальное описание",
  WarehouseBrw: "Склады",
  SysParamsbrw: "Системные параметры",
  CameraTreeBrw: "Система охраны",
  DocGroupDocumentsBrw: "Связанные документы",
  Regions: "Регионы",
  Docks: "Рампы",
  RF: "Радио терминалы",
  VISION_BROWSERS: "Программы Vision",
  PrintersBrw: "Принтеры",
  StorageRulesBrw: "Правила хранения",
  TransportFunctionZonesBrw: "Правила транспортировки",
  ProductivityRulesBrw: "Правила продуктивности",
  CourierParcelsBrw: "Посылки курьеров",
  UserScriptsBrw: "Пользовательские скрипты",
  UserManagerbrw: "Пользователи",
  PermReservationsBrw: "Периодические резервации",
  Partners: "Партнёры",
  SkuLotBrw: "Партии товаров",
  ReportsBrw: "Отчёты",
  Shipments: "Отгрузки",
  ConsolidationRestrictionsBrw: "Ограничения консолидации",
  Equipmentbrw: "Оборудование",
  InboundOverview: "Обзор приёмки",
  OutboundOverview: "Обзор отгрузки",
  MixRulesBrw: "Методы хранения",
  CourierManifestsBrw: "Манифесты курьеров",
  ModuleLicenceVw: "Лицензии модулей",
  CourierVASGroupsBrw: "Курьеры группы услуг",
  CouriersBrw: "Курьеры",
  CourierClientConfigBrw: "Конфигурация курьеров",
  JobContextsBrw: "Контексты фонового процесса",
  CommunicationFilesBrw: "Коммуникационные файлы",
  CommunicationErrorBrw: "Коммуникационные сообщения",
  ReasonCodesbrw: "Коды причин",
  SKUClassBrw: "Классы",
  SkuCategoriesBrw: "Категории сортировки",
  Sku: "Карточки товаров",
  Locationtreebrw: "Карта ячеек",
  LocationListTreeBrw: "Карта склада 2",
  OrderProcessingLog: "История сортировки/сборки",
  CourierCommLogBrw: "История коммуникаций курьера",
  ErpTransitionHistoryBrw: "История изменения ERP склада",
  ActionLogbrw: "История действий",
  InvHistoryBrw: "История движения товаров",
  ConsolidationCandidatesBrw: "Информация консолидации",
  SortSysOrders: "Заказы сортировки",
  SysOrders: "Заказы сборки",
  InOrdersbrw: "Заказы приёмки",
  DistOrders: "Заказы отгрузки",
  CourierOrdersBrw: "Заказы курьеров",
  StockTakingDocBrw: "Заказы инвентаризации",
  WorkOrdersbrw: "Задания работы",
  MeasureUnits: "Единицы измерения",
  BrowserDeliveries: "Доставки",
  Skutreebrw: "Дерево товаров",
  MixGroupsBrw: "Группы сортировки",
  SequenceGeneratorBrw: "Генерирование последовательностей для ячеек",
  InternalMoves: "Внутренние перемещения",
  CurrenciesBrw: "Валюты",
  JobBlockersBrw: "Блокирующие фон. процессы",
  Holdsbrw: "Блокировки",
  DistLoadsBrw: "Аккаунты",
  Erpwarehousesbrw: "ERP склады",
};
